apiVersion: v1
kind: Pod
metadata:
  name: sampledemo
  namespace: javacop
  labels:
    app: sampledemo
spec:
  containers:
    - name:  sampledemo-container
      image: artifactory.transunion.com/docker-dev-local/javacop/sampledemo:v1
      ports:
       - containerPort: 8080
  imagePullSecrets:
    - name: artifactory-cred

