apiVersion: v1
kind: Service
metadata:
  name: sampledemo-service
  labels:
    name: sampledemo
  namespace: javacop
spec:
  type: NodePort
  selector:
    app: sampledemo
  ports:
    -
      name: http
      port: 80
      targetPort: 8080
